version: '3'

services:
  database:
    image: mongodb/mongodb-atlas-local:latest
    hostname: database
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
